var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,f,c){a instanceof String&&(a=String(a));for(var g=a.length,h=0;h<g;h++){var e=a[h];if(f.call(c,e,h,a))return{i:h,v:e}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,c){a!=Array.prototype&&a!=Object.prototype&&(a[f]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,f,c,g){if(f){c=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var h=a[g];h in c||(c[h]={});c=c[h]}a=a[a.length-1];g=c[a];f=f(g);f!=g&&null!=f&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:f})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
(function(){var a=[],f=0;window.generate_the_wcmp=function(c){function g(d){if(d+1<f){var b=d+1;a[b]instanceof e&&a[b].is("a")?a[b].is(":visible")?a[b].click():g(d+1):e(a[b].container).is(":visible")?a[b].play():g(d+1)}}function h(a){var b=a.data("product"),d=e("img.product-"+b);d.length&&1==e('[data-product="'+b+'"]').length&&(b=d.offset(),a=a.closest("div.wcmp-player"),a.css({position:"absolute","z-index":999999}).offset({left:b.left+(d.width()-a.width())/2,top:b.top+(d.height()-a.height())/2}))}
if(!("boolean"!==typeof c&&"undefined"!=typeof wcmp_global_settings&&1*wcmp_global_settings.onload)&&"undefined"===typeof generated_the_wcmp){generated_the_wcmp=!0;var e=jQuery;e(document).on("click",".wcmp-player-container",function(a){a.preventDefault();a.stopPropagation()});e.expr[":"].regex=function(a,b,c){b=c[3].split(",");var d=/^(data|css):/;c=b[0].match(d)?b[0].split(":")[0]:"attr";d=b.shift().replace(d,"");return(new RegExp(b.join("").replace(/^\s+|\s+$/g,""),"ig")).test(e(a)[c](d))};var n=
"undefined"!=typeof wcmp_global_settings?wcmp_global_settings.play_all:!0,k="undefined"!=typeof wcmp_global_settings?!(1*wcmp_global_settings.play_simultaneously):!0,m="undefined"!=typeof wcmp_global_settings&&"ios_controls"in wcmp_global_settings&&1*wcmp_global_settings.ios_controls?!0:!1;c=e("audio.wcmp-player:not(.track):not([playernumber])");var p=e("audio.wcmp-player.track:not([playernumber])"),l={pauseOtherPlayers:k,iPadUseNativeControls:m,iPhoneUseNativeControls:m,success:function(a,b){e(b).attr("volume")&&
a.setVolume(parseFloat(e(b).attr("volume")));var d=function(a){a=e(a.target);var b=a.data("duration");"undefined"!=typeof b&&a.closest(".wcmp-player-container").find(".mejs-duration").html(b)};a.addEventListener("timeupdate",function(a){d(a);isNaN(this.currentTime)||isNaN(this.duration)||-1==this.src.indexOf("ms-action=secure")||(4>this.duration-this.currentTime?this.setVolume(this.volume-this.volume/3):("undefined"==typeof this.bkVolume&&(this.bkVolume=this.volume),this.setVolume(this.bkVolume)))});
a.addEventListener("volumechange",function(a){!isNaN(this.currentTime)&&!isNaN(this.duration)&&-1!=this.src.indexOf("ms-action=secure")&&4<this.duration-this.currentTime&&this.currentTime&&(this.bkVolume=this.volume)});a.addEventListener("ended",function(a){1*n&&(a=1*e(this).attr("playernumber"),g(a))});a.addEventListener("loadedmetadata",function(a){d(a)})}};k=".product-type-grouped :regex(name,quantity\\[\\d+\\])";c.each(function(){var d=e(this);d.find("source").attr("src");d.attr("playernumber",
f);f++;l.audioVolume="vertical";try{a[f]=new MediaElementPlayer(d[0],l)}catch(b){"console"in window&&console.log(b)}});p.each(function(){var d=e(this);d.find("source").attr("src");d.attr("playernumber",f);f++;l.features=["playpause"];try{a[f]=new MediaElementPlayer(d[0],l)}catch(b){"console"in window&&console.log(b)}h(d);e(window).resize(function(){h(d)})});e(k).length||(k=".product-type-grouped [data-product_id]");e(k).each(function(){var a=e(this),b=a.data("product_id")||a.attr("name").replace(/[^\d]/g,
"");b=e(".wcmp-player-list.merge_in_grouped_products .product-"+b+":first .wcmp-player-title");var c=e("<table></table>");b.length&&!b.closest(".wcmp-first-in-product").length&&(b.closest("tr").addClass("wcmp-first-in-product"),0==b.closest("form").length&&b.closest(".wcmp-player-list").prependTo(a.closest("form")),c.append(a.closest("tr").prepend("<td>"+b.html()+"</td>")),b.html("").append(c))})}};window.wcmp_force_init=function(){delete window.generated_the_wcmp;generate_the_wcmp(!0)};jQuery(generate_the_wcmp);
jQuery(window).on("load",function(){generate_the_wcmp(!0);var a=jQuery,f=window.navigator.userAgent;a("[data-lazyloading]").each(function(){var c=a(this);c.attr("preload",c.data("lazyloading"))});if(f.match(/iPad/i)||f.match(/iPhone/i))if("undefined"!=typeof wcmp_global_settings?wcmp_global_settings.play_all:1)a(".wcmp-player .mejs-play button").one("click",function(){if("undefined"==typeof wcmp_preprocessed_players){wcmp_preprocessed_players=!0;var c=a(this);a(".wcmp-player audio").each(function(){this.play();
this.pause()});setTimeout(function(){c.click()},500)}})}).on("popstate",function(){jQuery("audio[data-product]:not([playernumber])").length&&wcmp_force_init()});jQuery(document).on("scroll",wcmp_force_init)})();
